name = "PhyloTrees"
uuid = "000eca47-99c6-4e5b-a526-041c0fe32828"
authors = ["justin <justinangevaare@gmail.com>"]
version = "0.9.0"

[deps]
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
SubstitutionModels = "8365b1bb-bd83-58ee-a267-f2965fc81c73"

[compat]
julia = "≥ 1.0.0"
