name = "PhyloTrees"
uuid = "000eca47-99c6-4e5b-a526-041c0fe32828"
authors = ["justin <justinangevaare@gmail.com>"]
version = "0.10.0"

[compat]
julia = "≥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
